# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/My Drive/College/alexnet-ai-accelerator/vivado_systolic/vivado_systolic.srcs/sources_1/ip/CORTEXM3_AXI_0/CORTEXM3_AXI_0.xci
# IP: The module: 'CORTEXM3_AXI_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/My Drive/College/alexnet-ai-accelerator/vivado_systolic/vivado_systolic.gen/sources_1/ip/CORTEXM3_AXI_0/CORTEXM3_AXI_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CORTEXM3_AXI_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: g:/My Drive/College/alexnet-ai-accelerator/vivado_systolic/vivado_systolic.srcs/sources_1/ip/CORTEXM3_AXI_0/CORTEXM3_AXI_0.xci
# IP: The module: 'CORTEXM3_AXI_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/My Drive/College/alexnet-ai-accelerator/vivado_systolic/vivado_systolic.gen/sources_1/ip/CORTEXM3_AXI_0/CORTEXM3_AXI_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CORTEXM3_AXI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
